experiment_name: 'mica_concept_classifier_CBM'
phase: 'classification_CBM'
trial_name:

lightning:
    trainer:
       gpus: [0]
       max_epochs: 100
       min_epochs: 100
       distributed_backend: 'dp'
       gradient_clip_val: 0.25
       lr: 1e-4
       precision: 16
    checkpoint_callback:
        monitor: 'val_loss'
        dirpath: '/path/ckpt'  # NOTE: modify the checkpoint path
        save_last: false
        mode: min
        every_n_epochs: 10

    early_stopping_callback:
        monitor: 'val_loss'
        min_delta: 0.00
        patience: 10
        verbose: False
        mode: 'min'
    logger:
        logger_type: 'WandbLogger'
        save_dir: './out/'
        project: 'mica_classification'

model: 
    vision:
        model_name: 'mica_resnet50'
        freeze_cnn: true
        pretrained: false
        num_targets: -1  # NOTE: set the number of concepts
    checkpoint: "/path.ckpt"  # NOTE: modify the checkpoint path

data: 
    dataset: dataset_name_CBM  # NOTE: modify the dataset name
    image:
        imsize: 256
    frac: 1
    concept:
        num: 7

transforms: 
    norm: 'half'
    random_crop:
        crop_size: 224
    random_horizontal_flip: 0.5
    random_affine:
        degrees: [-10, 10]
        translate: [0.0625, 0.0625]
        scale: [0.8, 1.1]
    color_jitter:
        brightness: [0.5, 1.2]
        contrast: [0.5, 1.2]

train: 
    batch_size: 32
    num_workers: 8 
    loss_fn: 
        type: BCE
        class_weights:
    optimizer: 
        name: 'Adam'
        weight_decay: 1e-6
    scheduler: 
        name: 'plateau'
        monitor: 'val_loss'
        interval: 'epoch'
        frequency: 3